/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.TelasDeRelatorio;

import Classes.Passageiro;
import Telas.TelaPrincipal;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.postgresql.core.ConnectionFactory;

/**
 *
 * @author Jeff
 */
public class TelaDeRelatorios extends javax.swing.JFrame {
   
    /**
     * Creates new form TelaDeRelatorios
     */
    public TelaDeRelatorios() {
        initComponents();
        System.out.println(System.getProperties());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelPassageiros = new javax.swing.JButton();
        btnRelMotoristas = new javax.swing.JButton();
        btnRelViagens = new javax.swing.JButton();
        btnVoltar3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRelatorioGeral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRelPassageiros.setText("Relatório de Passageiros");
        btnRelPassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPassageirosActionPerformed(evt);
            }
        });

        btnRelMotoristas.setText("Relatório de Motoristas");
        btnRelMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelMotoristasActionPerformed(evt);
            }
        });

        btnRelViagens.setText("Relatório de Viagens");
        btnRelViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelViagensActionPerformed(evt);
            }
        });

        btnVoltar3.setText("Voltar");
        btnVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar3ActionPerformed(evt);
            }
        });

        jButton1.setText("Relatório de Onibus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Relatórios");

        btnRelatorioGeral.setText("Relatório Geral De Viagens");
        btnRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioGeralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(329, Short.MAX_VALUE)
                        .addComponent(btnVoltar3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelViagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelMotoristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelPassageiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorioGeral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnRelatorioGeral)
                .addGap(18, 18, 18)
                .addComponent(btnRelPassageiros)
                .addGap(18, 18, 18)
                .addComponent(btnRelMotoristas)
                .addGap(18, 18, 18)
                .addComponent(btnRelViagens)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(btnVoltar3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

     
    private void btnRelPassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPassageirosActionPerformed

        // TODO add your handling code here:
        HashMap map = new HashMap(); 
        JasperPrint impressao = null; 
        try { 
            impressao = JasperFillManager.fillReport(System.getProperty("user.dir")+"/src/relatorio/RelatorioDePassageiros.jasper", map, AcessaBD.connection);
        } catch (JRException ex) {
            System.err.println("Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(impressao, false);
        view.setVisible(true);

    }//GEN-LAST:event_btnRelPassageirosActionPerformed

    private void btnRelViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelViagensActionPerformed
        // TODO add your handling code here:
        HashMap map = new HashMap(); 
        JasperPrint impressao = null; 
        try { 
            impressao = JasperFillManager.fillReport(System.getProperty("user.dir")+"/src/relatorio/RelatorioDeViagens.jasper", map, AcessaBD.connection);
        } catch (JRException ex) {
            System.err.println("Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(impressao, false);
        view.setVisible(true);
    }//GEN-LAST:event_btnRelViagensActionPerformed

    private void btnVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar3ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        TelaDeRelatorios t = new TelaDeRelatorios();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltar3ActionPerformed

    private void btnRelMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelMotoristasActionPerformed
        // TODO add your handling code here:
        HashMap map = new HashMap(); 
        JasperPrint impressao = null; 
        try { 
            impressao = JasperFillManager.fillReport(System.getProperty("user.dir")+"/src/relatorio/RelatorioDeMotoristas.jasper", map, AcessaBD.connection);
        } catch (JRException ex) {
            System.err.println("Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(impressao, false);
        view.setVisible(true);
    }//GEN-LAST:event_btnRelMotoristasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HashMap map = new HashMap(); 
        JasperPrint impressao = null; 
        try { 
            impressao = JasperFillManager.fillReport(System.getProperty("user.dir")+"/src/relatorio/RelatorioDeOnibus.jasper", map, AcessaBD.connection);
        } catch (JRException ex) {
            System.err.println("Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(impressao, false);
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioGeralActionPerformed
        // TODO add your handling code here:
        HashMap map = new HashMap(); 
        JasperPrint impressao = null; 
        try { 
            impressao = JasperFillManager.fillReport(System.getProperty("user.dir")+"/src/relatorio/RelatorioValorTotal.jasper", map, AcessaBD.connection);
        } catch (JRException ex) {
            System.err.println("Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(impressao, false);
        view.setVisible(true);
    }//GEN-LAST:event_btnRelatorioGeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelMotoristas;
    private javax.swing.JButton btnRelPassageiros;
    private javax.swing.JButton btnRelViagens;
    private javax.swing.JButton btnRelatorioGeral;
    private javax.swing.JButton btnVoltar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
