package Telas.TelasDeCadastro;

import Classes.Motorista;
import Classes.Passageiro;
import Classes.Viagem;
import ClassesDAO.MotoristaDAO;
import ClassesDAO.PassageiroDAO;
import ClassesDAO.ViagemDAO;
import Controller.HibernateUtil;
import Telas.TelaPrincipal;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.AnnotationConfiguration;


public class TelaCadastroViagem extends javax.swing.JFrame {

    public TelaCadastroViagem() {
        initComponents();
        popularJcbMotorista();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void popularJcbMotorista(){
        MotoristaDAO motDAO = new MotoristaDAO(HibernateUtil.getSession());

        if (motDAO.listaTudo() != null){
            for (Motorista mot : motDAO.listaTudo()){
                jcbMotorista.addItem(mot.getNome());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroDePassageiro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblDataSaida = new javax.swing.JLabel();
        jtfDataSaida = new javax.swing.JTextField();
        lblDataChegada = new javax.swing.JLabel();
        jtfDataChegada = new javax.swing.JTextField();
        lblHoraSaida = new javax.swing.JLabel();
        jtfHoraSaida = new javax.swing.JTextField();
        lblHoraChegada = new javax.swing.JLabel();
        jtfHoraChegada = new javax.swing.JTextField();
        lblMotorista = new javax.swing.JLabel();
        jcbMotorista = new javax.swing.JComboBox<>();
        lblCidadeSaida = new javax.swing.JLabel();
        jtfCidadeSaida = new javax.swing.JTextField();
        lblCidadeSaida1 = new javax.swing.JLabel();
        jtfCidadeChegada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastroDePassageiro.setText("Cadastro de Viagem");

        lblNome.setText("Preço:");

        jtfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblDataSaida.setText("Data Saída:");

        jtfDataSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataSaidaActionPerformed(evt);
            }
        });

        lblDataChegada.setText("Data Chegada:");

        jtfDataChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataChegadaActionPerformed(evt);
            }
        });

        lblHoraSaida.setText("Hora Saída:");

        jtfHoraSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHoraSaidaActionPerformed(evt);
            }
        });

        lblHoraChegada.setText("Hora Chegada:");

        jtfHoraChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHoraChegadaActionPerformed(evt);
            }
        });

        lblMotorista.setText("Motorista");

        lblCidadeSaida.setText("Cidade Saída:");

        jtfCidadeSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeSaidaActionPerformed(evt);
            }
        });

        lblCidadeSaida1.setText("Cidade Chegada:");

        jtfCidadeChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeChegadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraChegada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHoraSaida)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDataSaida)
                                        .addComponent(lblDataChegada))
                                    .addComponent(lblNome)
                                    .addComponent(lblMotorista))
                                .addComponent(lblCidadeSaida)
                                .addComponent(lblCidadeSaida1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCidadeSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(jtfPreco)
                                .addComponent(jtfDataChegada, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfHoraSaida, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfDataSaida)
                                .addComponent(jcbMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCidadeChegada, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(jtfHoraChegada)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnVoltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblCadastroDePassageiro)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroDePassageiro)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataSaida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataChegada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraSaida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraChegada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeSaida)
                    .addComponent(jtfCidadeSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeSaida1)
                    .addComponent(jtfCidadeChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMotorista))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
      
        try {
            if (jtfDataChegada.getText().equals("")|| jtfDataSaida.getText().equals ("")|| 
                    jtfHoraSaida.getText().equals ("")|| jtfHoraChegada.getText().equals ("")|| 
                    jtfCidadeChegada.getText().equals ("")|| jtfCidadeSaida.getText().equals ("")||
                    jtfPreco.getText().equals("")){
                throw new Exception ("Nao deve conter campos nulo");
            }
            Viagem v = new Viagem();
            
            v.setCidadeSaida(jtfCidadeSaida.getText());
            v.setCidadeChegada(jtfCidadeChegada.getText());
            v.setDataChegada(jtfDataChegada.getText());
            v.setDataSaida(jtfDataSaida.getText());
            v.setHoraChegada(jtfHoraChegada.getText());
            v.setHoraSaida(jtfHoraSaida.getText());
            v.setPreco(Float.parseFloat(jtfPreco.getText()));
            
            Session session = HibernateUtil.getSession();
            ViagemDAO dao = new ViagemDAO(session);
            
            dao.salva(v);
            LimparTela();
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed
 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jtfDataSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataSaidaActionPerformed

    private void jtfDataChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataChegadaActionPerformed

    private void jtfHoraSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHoraSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHoraSaidaActionPerformed

    private void jtfHoraChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHoraChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHoraChegadaActionPerformed

    private void jtfCidadeSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCidadeSaidaActionPerformed

    private void jtfCidadeChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCidadeChegadaActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroViagem().setVisible(true);
            }
        });  
    }
    public void LimparTela () {

        jtfCidadeChegada.setText("");
        jtfCidadeSaida.setText("");
        jtfDataSaida.setText("");
        jtfDataChegada.setText("");
        jtfHoraSaida.setText("");
        jtfHoraChegada.setText("");
        jtfPreco.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jcbMotorista;
    private javax.swing.JTextField jtfCidadeChegada;
    private javax.swing.JTextField jtfCidadeSaida;
    private javax.swing.JTextField jtfDataChegada;
    private javax.swing.JTextField jtfDataSaida;
    private javax.swing.JTextField jtfHoraChegada;
    private javax.swing.JTextField jtfHoraSaida;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JLabel lblCadastroDePassageiro;
    private javax.swing.JLabel lblCidadeSaida;
    private javax.swing.JLabel lblCidadeSaida1;
    private javax.swing.JLabel lblDataChegada;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblHoraChegada;
    private javax.swing.JLabel lblHoraSaida;
    private javax.swing.JLabel lblMotorista;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
