package Telas.TelasDeCadastro;


import Telas.TelasDeCadastro.TelaCadastroMotorista;
import Telas.TelaPrincipal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeff
 */
public class TelaDeCadastros extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastros
     */
    public TelaDeCadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastroPassageiro = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnCadastrarMotorista = new javax.swing.JButton();
        btnCadastroOnibus = new javax.swing.JButton();
        btnCadastroViagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastroPassageiro.setText("Cadastrar Passageiro");
        btnCadastroPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPassageiroActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrarMotorista.setText("Cadastrar Motorista");
        btnCadastrarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMotoristaActionPerformed(evt);
            }
        });

        btnCadastroOnibus.setText("Cadastrar Onibus");
        btnCadastroOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroOnibusActionPerformed(evt);
            }
        });

        btnCadastroViagem.setText("Cadastrar Viagem");
        btnCadastroViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroViagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCadastroPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroOnibus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnCadastroPassageiro)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarMotorista)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroOnibus)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroViagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPassageiroActionPerformed
        // TODO add your handling code here:
        TelaCadastroPassageiro tela = new TelaCadastroPassageiro();
        TelaDeCadastros t = new TelaDeCadastros();
        tela.setVisible(true);
        this.dispose();
 
    }//GEN-LAST:event_btnCadastroPassageiroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        TelaDeCadastros t = new TelaDeCadastros();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMotoristaActionPerformed
        // TODO add your handling code here:
        TelaCadastroMotorista tela = new TelaCadastroMotorista();
        TelaDeCadastros t = new TelaDeCadastros();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarMotoristaActionPerformed

    private void btnCadastroOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroOnibusActionPerformed
        // TODO add your handling code here:
        TelaCadastroOnibus tela = new TelaCadastroOnibus();
        TelaDeCadastros t = new TelaDeCadastros();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastroOnibusActionPerformed

    private void btnCadastroViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroViagemActionPerformed
        // TODO add your handling code here:
        TelaCadastroViagem tela = new TelaCadastroViagem();
        TelaDeCadastros t = new TelaDeCadastros();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastroViagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarMotorista;
    private javax.swing.JButton btnCadastroOnibus;
    private javax.swing.JButton btnCadastroPassageiro;
    private javax.swing.JButton btnCadastroViagem;
    private javax.swing.JButton btnVoltar;
    // End of variables declaration//GEN-END:variables
}
