/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.TelasDeConsulta;

import Telas.TelaPrincipal;

/**
 *
 * @author Jeff
 */
public class TelaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultar
     */
    public TelaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnconsultarpassageiro = new javax.swing.JButton();
        btnConsultarMotorista = new javax.swing.JButton();
        btnConsultarOnibus = new javax.swing.JButton();
        btnConsultarViagens = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnconsultarpassageiro.setText("Consultar Passageiro");
        btnconsultarpassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarpassageiroActionPerformed(evt);
            }
        });

        btnConsultarMotorista.setText("Consultar Motorista");
        btnConsultarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMotoristaActionPerformed(evt);
            }
        });

        btnConsultarOnibus.setText("Consultar Onibus");
        btnConsultarOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOnibusActionPerformed(evt);
            }
        });

        btnConsultarViagens.setText("Consultar Viagens");
        btnConsultarViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarViagensActionPerformed(evt);
            }
        });

        btnSair.setText("Voltar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnconsultarpassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarOnibus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarViagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnconsultarpassageiro)
                .addGap(39, 39, 39)
                .addComponent(btnConsultarMotorista)
                .addGap(32, 32, 32)
                .addComponent(btnConsultarOnibus)
                .addGap(32, 32, 32)
                .addComponent(btnConsultarViagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarpassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarpassageiroActionPerformed
        // TODO add your handling code here:
        TelaConsultaPassageiro tela = new TelaConsultaPassageiro();
        TelaConsultar t = new TelaConsultar();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnconsultarpassageiroActionPerformed

    private void btnConsultarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMotoristaActionPerformed
        // TODO add your handling code here:
        TelaConsultaMotorista tela = new TelaConsultaMotorista();
        TelaConsultar t = new TelaConsultar();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarMotoristaActionPerformed

    private void btnConsultarOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOnibusActionPerformed
        // TODO add your handling code here:
        TelaConsultaOnibus tela = new TelaConsultaOnibus();
        TelaConsultar t = new TelaConsultar();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarOnibusActionPerformed

    private void btnConsultarViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarViagensActionPerformed
        // TODO add your handling code here:
        TelaConsultar t = new TelaConsultar();
        TelaConsultaViagem tela = new TelaConsultaViagem();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarViagensActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        TelaConsultar t = new TelaConsultar();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarMotorista;
    private javax.swing.JButton btnConsultarOnibus;
    private javax.swing.JButton btnConsultarViagens;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnconsultarpassageiro;
    // End of variables declaration//GEN-END:variables
}
